- name: python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: python
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup


- name: python
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd